# Continue configuration for continue setup
setup: true

version: 2.1

# Dynamic configuration for complex workflows
orbs:
  continuation: circleci/continuation@1.0.0

jobs:
  setup_dynamic_config:
    executor: continuation/default
    steps:
      - checkout
      - run:
          name: Generate dynamic configuration
          command: |
            # Determine what components changed
            if git diff --name-only HEAD~1 | grep -E "(src/protocol|include/protocol)"; then
              echo "export PROTOCOL_CHANGED=true" >> dynamic_config_env
            fi
            
            if git diff --name-only HEAD~1 | grep -E "(src/database|include/database)"; then
              echo "export DATABASE_CHANGED=true" >> dynamic_config_env
            fi
            
            if git diff --name-only HEAD~1 | grep -E "(src/network|include/network)"; then
              echo "export NETWORK_CHANGED=true" >> dynamic_config_env
            fi
            
            # Generate conditional pipeline
            cat > .circleci/generated_config.yml << 'EOF'
            version: 2.1
            
            workflows:
              conditional_build:
                when:
                  or:
                    - equal: [ "true", << pipeline.parameters.protocol_changed >> ]
                    - equal: [ "true", << pipeline.parameters.database_changed >> ]
                    - equal: [ "true", << pipeline.parameters.network_changed >> ]
                jobs:
                  - build_and_test
            
            parameters:
              protocol_changed:
                type: boolean
                default: false
              database_changed:
                type: boolean
                default: false
              network_changed:
                type: boolean
                default: false
            
            jobs:
              build_and_test:
                docker:
                  - image: cimg/base:2024.02
                steps:
                  - run: echo "Running conditional build"
            EOF

      - continuation/continue:
          configuration_path: .circleci/generated_config.yml
          parameters: |
            {
              "protocol_changed": ${PROTOCOL_CHANGED:-false},
              "database_changed": ${DATABASE_CHANGED:-false}, 
              "network_changed": ${NETWORK_CHANGED:-false}
            }

workflows:
  setup_workflow:
    jobs:
      - setup_dynamic_config
