[server]
host = "127.0.0.1"
port = 27018
max_connections = 1000
connection_timeout_ms = 5000
idle_timeout_ms = 60000

[database]
uri = "postgresql://localhost:5432/fauxdb"
max_connections = 10
connection_timeout_ms = 5000
idle_timeout_ms = 60000
enable_jsonb_extensions = true

[logging]
level = "info"
format = "json"
output = "stdout"

[metrics]
enabled = true
port = 9090
path = "/metrics"

[ssl]
enabled = false
cert_file = ""
key_file = ""
ca_file = ""
verify_mode = "peer"
min_tls_version = "1.2"
max_tls_version = "1.3"
cipher_suites = ["TLS_AES_256_GCM_SHA384", "TLS_CHACHA20_POLY1305_SHA256", "TLS_AES_128_GCM_SHA256"]
allow_insecure = false
client_cert_required = false
sni_enabled = true

[authentication]
enabled = true
default_auth_method = "SCRAM-SHA-256"
session_timeout_minutes = 30
max_sessions_per_user = 10

[authentication.password_policy]
min_length = 8
require_uppercase = true
require_lowercase = true
require_numbers = true
require_special_chars = true
max_age_days = 90

[authentication.ldap]
server_url = ""
base_dn = ""
bind_dn = ""
bind_password = ""
user_search_filter = ""
group_search_filter = ""

[authentication.kerberos]
realm = ""
keytab_file = ""
service_principal = ""