server:
  port: 27017
  bind_address: "0.0.0.0"
  max_connections: 1000
  worker_threads: 4
  daemon_mode: false

postgresql:
  host: "localhost"
  port: "5432"
  database: "fauxdb"
  user: "fauxdb"
  password: "fauxdb"
  pool_size: 10
  timeout: 10

client_auth:
  method: "scram-sha-256"
  required: true
  database: "admin"
  username: "admin"
  password: "admin123"
  use_ssl: false
  ssl_cert: ""
  ssl_key: ""
  ssl_ca: ""

server_auth:
  method: "basic"
  required: true
  database: "fauxdb"
  username: "fauxdb"
  password: "fauxdb123"
  use_ssl: false
  ssl_cert: ""
  ssl_key: ""
  ssl_ca: ""

logging:
  log_file: "fauxdb.log"
  log_level: "INFO"
  verbose: false
  debug: false

performance:
  query_cache_enabled: true
  query_cache_size: 1000
