# GitHub Pages Configuration for FauxDB Documentation

title: FauxDB Documentation
description: MongoDB-compatible server built on PostgreSQL with production-ready features
author: pgElephant Team
email: contact@pgelephant.org

# GitHub Pages settings
baseurl: "/fauxdb"
url: "https://pgelephant.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - _site/
  - .sass-cache/
  - .jekyll-cache/
  - .jekyll-metadata
  - .bundle/
  - .git/
  - .gitignore
  - .ruby-version
  - .ruby-gemset
  - .rvmrc
  - .DS_Store
  - Thumbs.db

# Include files
include:
  - _redirects

# Collections
collections:
  api:
    output: true
    permalink: /:collection/:name/
  examples:
    output: true
    permalink: /:collection/:name/

# Default settings
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  - scope:
      path: ""
      type: "api"
    values:
      layout: "api"
  - scope:
      path: ""
      type: "examples"
    values:
      layout: "example"

# SEO settings
twitter:
  username: pgelephant

github:
  username: pgelephant
  repository: fauxdb

# Navigation
navigation:
  - title: Home
    url: /
  - title: Quick Start
    url: /quick-start/
  - title: Installation
    url: /installation/
  - title: API Reference
    url: /api/
  - title: Examples
    url: /examples/
  - title: GitHub
    url: https://github.com/pgelephant/fauxdb
    external: true

# Social links
social:
  - name: GitHub
    url: https://github.com/pgelephant/fauxdb
  - name: Twitter
    url: https://twitter.com/pgelephant

# Analytics (optional)
# google_analytics: UA-XXXXXXXXX-X

# Search
search: true
search_full_content: true

# Comments (optional)
# disqus:
#   shortname: fauxdb-docs